name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    name: Build & Test (Go 1.24)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Download Go Modules
        run: go mod download

      - name: 🔨 Build Project
        run: go build -v ./...

      - name: 🧪 Run Unit Tests (with Race Detector)
        run: go test -v -race ./...

      - name: 🧹 Run Go Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
          only-new-issues: true
