name: Go CI / Lint & Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.21", "1.22"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Download Go Modules
        run: go mod download

      - name: 🔨 Build Project
        run: go build -v ./...

      - name: 🧪 Run Unit Tests
        run: go test -v ./...
      - name: 🧹 Run Go Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
          only-new-issues: true
